### ISSUE TITLE
python 코드 업데이트

### ISSUE THREAD

**Issue by CHANWOO97** [CHANWOO97/github_gui_with_issac#3]
코드 업데이트 진행해주세요.
issac 개발자님 

업데이트 시 이슈 close 하겠습니다.

**Comment by issac527** [comment]
isac 브란치에 python 코드 올렸습니다~

**Comment by CHANWOO97** [comment]
업무에 노고가 많으십니다!
항상 만수무강 하세요

**Comment by issac527** [comment]
백년해로 하겠습니다^^
